name: Manually generate documentation

on:
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "update-documentation"
  cancel-in-progress: true

jobs:
  generate-documentation:
    name: Generate documentation for release
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/library-documentation-action-v2-insiders:release
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Generate documentation
        run: /entrypoint.py
        env:
          INPUT_SITE_URL: "https://ponylang.github.io/http/"
          INPUT_LIBRARY_NAME: "http"
          INPUT_DOCS_BUILD_DIR: "build/http-docs"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/http-docs/site/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
