name: PR

on:
  pull_request:
    paths:
      - '**'
      - '!**/*.md'
      - '!**/*.yml'
      - '!**/*.yaml'
      - '.github/workflows/pr.yml'

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  libressl-3-vs-ponyc-release:
    name: LibreSSL 3.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.9.2:release
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Test
        run: make test config=debug ssl=libressl

  libressl-4-vs-ponyc-release:
    name: LibreSSL 4.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-libressl-4.2.1:release
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Test
        run: make test config=debug ssl=libressl

  openssl-1-vs-ponyc-release:
    name: OpenSSL 1.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1w:release
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Test
        run: make test config=debug ssl=1.1.x

  openssl-3-vs-ponyc-release:
    name: OpenSSL 3.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-standard-builder-with-openssl-3.6.2:release
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Test
        run: make test config=debug ssl=3.0.x

  windows-x86-64-vs-ponyc-release:
    name: Windows x86-64 with most recent ponyc release
    runs-on: windows-2025
    steps:
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true
      - uses: actions/checkout@v6.0.2
      - name: Test against recent ponyc release on Windows
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Force -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-x86-64-pc-windows-msvc.zip -OutFile C:\corral.zip;
          Expand-Archive -Force -Path C:\corral.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
      - name: Cache LibreSSL libs
        id: cache-libressl
        uses: actions/cache@v5.0.3
        with:
          path: |
            ssl.lib
            crypto.lib
            tls.lib
          key: libressl-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.ci-scripts/windows-install-libressl.ps1') }}
      - name: Install LibreSSL
        if: steps.cache-libressl.outputs.cache-hit != 'true'
        run: .ci-scripts\windows-install-libressl.ps1
      - name: Test
        run: |
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command test 2>&1;

  windows-arm64-vs-ponyc-release:
    name: Windows arm64 with most recent ponyc release
    runs-on: windows-11-arm
    steps:
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true
      - uses: actions/checkout@v6.0.2
      - name: Test against recent ponyc release on Windows
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-arm64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Force -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/corral-arm64-pc-windows-msvc.zip -OutFile C:\corral.zip;
          Expand-Archive -Force -Path C:\corral.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
      - name: Cache LibreSSL libs
        id: cache-libressl
        uses: actions/cache@v5.0.3
        with:
          path: |
            ssl.lib
            crypto.lib
            tls.lib
          key: libressl-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.ci-scripts/windows-install-libressl.ps1') }}
      - name: Install LibreSSL
        if: steps.cache-libressl.outputs.cache-hit != 'true'
        run: .ci-scripts\windows-install-libressl.ps1
      - name: Test
        run: |
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command test 2>&1;
